## Site settings
title: Without Head Or Foot
author: Cato Sandford
email: cato@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  Each one of us harbours mysteries and delights, unique experiences and thirsty curiosities;
  and what better way to exalt in our deepest enthusiasms than to write a mediocre blog that 
  not a single soul will read?
  No better way.
baseurl: "/WithoutHeadOrFoot" # the subpath of your site, e.g. /blog/
url: "Allium.github.io" # the base hostname & protocol for your site
timezone: America/New_ork

## Build settings
markdown: kramdown
highlighter: pygments

## Layout settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"