## Site settings
title: Without Head Or Foot
author: Cato Sandford
email: cato@catosandford.org
description: > # this means to ignore newlines
  Each one of us harbours mysteries and delights, unique experiences and thirsty curiosities;
  and what better way to exalt in our enthusiasms than to write a blog that 
  not a single soul will read?
  No better way!
description2: >
  A blog which yaws from topic to topic, depending on my momentary amateur interests. There'll be some things about the environment, the media, social justice, creative writing, and maybe even physics. So far the theme has been that I choose a topic on which I have next to no expertise and try to write something not totally idiotic about it.
  
baseurl: "/WithoutHeadOrFoot"
url:	"allium.github.io"

timezone: America/New_York

## Build settings
markdown: kramdown
highlighter: Rouge

## Layout settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
