## Site settings
title: Without Head Or Foot
author: Cato Sandford
email: cato@nyu.edu
description: > # this means to ignore newlines
  Each one of us harbours mysteries and delights, unique experiences and thirsty curiosities;
  and what better way to exalt in our deepest enthusiasms than to write a mediocre blog that 
  not a single soul will read?
  No better way!
description2: >
  This blog yaws from topic to topic, depending on my momentary amateur interests. There'll be some things about the environment, the media, social justice, creative writing, and maybe even physics...
baseurl: "/WithoutHeadOrFoot" # the subpath of your site, e.g. /blog/
url: "Allium.github.io" # the base hostname & protocol for your site
timezone: America/New_York

## Build settings
markdown: kramdown
highlighter: Rouge

## Layout settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"